### ISSUE TITLE
Single Quotes

### ISSUE THREAD

**Issue by MAGNAT2645** [clugg/sm-json#10]
I know this is probably a stupid idea but maybe you could add single quotes support for keys and string values like:

`{'testKey': 'testValue'}`

I want to add JSON-format objects via chat or client console but that's not working due to double quotes conflict.

**Comment by MAGNAT2645** [comment]
I mean, this would work only for json_decode function. After successfull decoding single quotes can be replaced with double (to avoid any MySQL errors etc.).

**Comment by clugg** [comment]
I have added optional support for parsing strings with single quotes. This is available as of [v2.2.0](../releases/tag/v2.2.0) and you can check the README for instructions to enable this option.
