### ISSUE TITLE
[Feature Req] implement function to convert Unicode escape sequences to Unicode characters

### ISSUE THREAD

**Issue by thboss** [clugg/sm-json#16]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
like convert `\u62b5` to `抵`

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by clugg** [comment]
I initially had no intention of supporting this, but the project is now at the stage where I think it is worthwhile to implement. I don't know a lot about the technical side of Unicode so this might take a couple of days to figure out.

**Comment by clugg** [comment]
I have just released [v3.1.0](../releases/tag/v3.1.0), which adds support for escaping and unescaping Unicode values (\uXXXX), as well as a few other changes. Please let me know how this goes, as I have not tested it extensively with real world data. Thanks for your suggestion!
