### ISSUE TITLE
[Bug]Int64 Not supported

### ISSUE THREAD

**Issue by mostten** [clugg/sm-json#25]
The original num is 2286852952, but decode num be converted to -2008114344.

**Comment by mostten** [comment]
> The original num is 2286852952, but decode num be conberted to -2008114344.

Sourcemod new api with "StringToInt64" can be use it?

**Comment by clugg** [comment]
Thanks for the suggestion! I've had a play with implementing this but I've encountered an issue with the new int64 natives along the way. I've submitted a PR to resolve this [here](https://github.com/alliedmodders/sourcemod/pull/1723) but I'll have to put this on hold until it's merged.

**Comment by mostten** [comment]
> Thanks for the suggestion! I've had a play with implementing this but I've encountered an issue with the new int64 natives along the way. I've submitted a PR to resolve this [here](https://github.com/alliedmodders/sourcemod/pull/1723) but I'll have to put this on hold until it's merged.

The dev build 6861 was fixed with your code.

**Comment by mostten** [comment]
> > Thanks for the suggestion! I've had a play with implementing this but I've encountered an issue with the new int64 natives along the way. I've submitted a PR to resolve this [here](https://github.com/alliedmodders/sourcemod/pull/1723) but I'll have to put this on hold until it's merged.
> 
> 
I made some changes on your old version, using strings to store Int64 to make it support Int64.

Now the Sourcemod dev build 6861 was fixed with your code, Please update json script, Thanks

**Comment by clugg** [comment]
I've just released [v4.0.0](../releases/tag/v4.0.0) which adds int64 support - you can find specific implementation details in the linked release notes. Here is the relevant documentation:
* [`JSON_Object`.`SetInt64`](https://clugg.github.io/sm-json/#content-json-object-methods-setint64)
* [`JSON_Object`.`GetInt64`](https://clugg.github.io/sm-json/#content-json-object-methods-getint64)
* [`JSON_Array`.`SetInt64`](https://clugg.github.io/sm-json/#content-json-array-methods-setint64)
* [`JSON_Array`.`GetInt64`](https://clugg.github.io/sm-json/#content-json-array-methods-getint64)
* [`JSON_Array`.`PushInt64`](https://clugg.github.io/sm-json/#content-json-array-methods-pushint64)
* [`JSONCellType`.`JSON_Type_Int64`](https://clugg.github.io/sm-json/#content-global-enums-jsoncelltype)

Thanks for your suggestion!
