### ISSUE TITLE
json_read_from_file handle is not closed

### ISSUE THREAD

**Issue by KillStr3aK** [clugg/sm-json#27]
The [file handle](https://github.com/clugg/sm-json/blob/03b1ebf3a275bf59b232381e925af5a1ee0b36d0/addons/sourcemod/scripting/include/json.inc#L716) shouldn't be closed after decoding?

**Comment by clugg** [comment]
Thanks for pointing this out! I've just released [v4.1.1](../releases/tag/v4.1.1) which resolves this issue.
